/**************************************************************************
 *  OMUGI - One More Ultimate Graph Implementation                        *
 *                                                                        *
 *  Copyright 2018: Shayne FLint, Jacques Gignoux & Ian D. Davies         *
 *       shayne.flint@anu.edu.au                                          * 
 *       jacques.gignoux@upmc.fr                                          *
 *       ian.davies@anu.edu.au                                            * 
 *                                                                        *
 *  OMUGI is an API to implement graphs, as described by graph theory,    *
 *  but also as more commonly used in computing - e.g. dynamic graphs.    *
 *  It interfaces with JGraphT, an API for mathematical graphs, and       *
 *  GraphStream, an API for visual graphs.                                *
 *                                                                        *
 **************************************************************************                                       
 *  This file is part of OMUGI (One More Ultimate Graph Implementation).  *
 *                                                                        *
 *  OMUGI is free software: you can redistribute it and/or modify         *
 *  it under the terms of the GNU General Public License as published by  *
 *  the Free Software Foundation, either version 3 of the License, or     *
 *  (at your option) any later version.                                   *
 *                                                                        *
 *  OMUGI is distributed in the hope that it will be useful,              *
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *  GNU General Public License for more details.                          *                         
 *                                                                        *
 *  You should have received a copy of the GNU General Public License     *
 *  along with OMUGI.  If not, see <https://www.gnu.org/licenses/gpl.html>*
 *                                                                        *
 **************************************************************************/
package fr.cnrs.iees.omugi.collections.tables;

import java.util.Arrays;

/**
 * A multidimensional table of {@code byte}s.
 * 
 * @author Shayne Flint - This code was generated by 
 * {@code fr.cnrs.iees.omugi.collections.tables/genPrimitiveClasses.py}
 * on Thu Aug 21 10:32:35 2014<br/>
 * modified by JG 15/2/2017 to account for {@link Table} and 
 * {@link fr.cnrs.iees.omhtk.DataContainer DataContainer} interfaces
 * */ 
public class ByteTable extends TableAdapter {

	protected byte[] data;

	/**
	 * Constructor with dimensioners
	 * 
	 * @param dimensions dimensioners
	 */
	public ByteTable(Dimensioner... dimensions) {
		super(dimensions);
		data = new byte[size()];
	}

	/** get the value stored at <em>indexes</em>*/
	public byte getByInt(int... indexes) {
		return data[getFlatIndexByInt(indexes)];
	}

	@Override
	public void setByInt(byte value, int... indexes) {
		data[getFlatIndexByInt(indexes)] = value;
	}

	/** get the value stored at flat <em>index</em>*/
	public byte getWithFlatIndex(int index) {
		return data[index];
	}

	@Override
	public void setWithFlatIndex(byte value, int index) {
		data[index] = value;
	}

	/** get the value stored at <em>indexes</em>*/
	public byte get(Object... indexes) {
		return data[getFlatIndex(indexes)];
	}

	@Override
	public void set(byte value, Object... indexes) {
		data[getFlatIndex(indexes)] = value;
	}

	@Override
	public ByteTable clone() {
		ByteTable result = cloneStructure();
		result.copy(this);
		return result;
	}
	
	@Override
	public ByteTable cloneStructure() {
		ByteTable result = new ByteTable(getDimensioners());
		return result;
	}

	/**
	 * Clone this table and fills it with its argument
	 * 
	 * @param initialValue the value to fill the table with
	 * @return the new table
	 */
	public ByteTable cloneStructure(byte initialValue) {
		ByteTable result = cloneStructure();
		result.fillWith(initialValue);
		return result;
	}
	
	@Override
	public ByteTable fillWith(byte value) {
		for (int i=0; i<data.length; i++)
			data[i] = value;
		return this;
	}
	
	@Override
	public String elementToString(int flatIndex) {
		return String.valueOf(data[flatIndex]);
	}

	@Override
	public ByteTable clear() {
		byte b = 00;
		fillWith(b); // this stupid dam thing wont accept a constant !
		return this;
	}

	@Override
	public ByteTable fillWith(Object value) {
		return fillWith(((Byte)value).byteValue());
	}

	@Override
	public ByteTable copy(Table from) {
		if (Byte.class.isAssignableFrom(from.contentType())) {
			ByteTable bt = (ByteTable)from;
			for (int i=0; i<data.length; i++)
				data[i] = bt.data[i];
		}
		return this;
	}

	@Override
	public String elementClassName() {
		return Byte.class.getName();
	}

	@Override
	public String elementSimpleClassName() {
		return Byte.class.getSimpleName();
	}

	@Override
	public Class<?> contentType() {
		return Byte.class;
	}
	
	/**
	 * Construct an instance from a {@code String} previously produced with 
	 * {@link TableAdapter#toSaveableString() toSaveableString()}. Uses the default block delimiters
	 * and item separators defined in {@link Table#getDefaultDelimiters()} 
	 * and {@link Table#getDefaultSeparators()}.
	 * 
	 * @param value the {@code String} to read data from
	 * @return the new instance
	 */
	public static ByteTable valueOf(String value) {
		return ByteTable.valueOf(value, Table.getDefaultDelimiters(), Table.getDefaultSeparators());
	}
	
	/**
	 * Construct an instance from a {@code String} previously produced with 
	 * {@link TableAdapter#toSaveableString toSaveableString(...)}.
	 * 
	 * @param value the {@code String} to read data from
	 * @param bdel block delimiters to use
	 * @param isep item separators to use
	 * @return the new instance
	 */
	public static ByteTable valueOf(String value, char[][] bdel, char[] isep) {
		String ss = TableAdapter.getBlockContent(value,bdel[TABLEix]);
		String d = ss.substring(0,ss.indexOf(bdel[DIMix][BLOCK_CLOSE])+1); 
		ByteTable result = new ByteTable(readDimensioners(d,bdel[DIMix],isep[DIMix]));
		ss = ss.substring(ss.indexOf(bdel[DIMix][BLOCK_CLOSE])+1);
		String s = null;
		int i=0;
		while (ss.indexOf(isep[TABLEix])>0) {
			s = ss.substring(0,ss.indexOf(isep[TABLEix]));
			ss = ss.substring(ss.indexOf(isep[TABLEix])+1);
			result.data[i] = Byte.valueOf(s);
			i++;
		}
		result.data[i] = Byte.valueOf(ss);
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		if (hash==0) {
			final int prime = 31;
			hash = super.hashCode();
			hash = prime * hash + Arrays.hashCode(data);
		}
		return hash;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (!(obj instanceof ByteTable))
			return false;
		ByteTable other = (ByteTable) obj;
		return Arrays.equals(data, other.data);
	}

}
