/**************************************************************************
 *  OMUGI - One More Ultimate Graph Implementation                        *
 *                                                                        *
 *  Copyright 2018: Shayne FLint, Jacques Gignoux & Ian D. Davies         *
 *       shayne.flint@anu.edu.au                                          * 
 *       jacques.gignoux@upmc.fr                                          *
 *       ian.davies@anu.edu.au                                            * 
 *                                                                        *
 *  OMUGI is an API to implement graphs, as described by graph theory,    *
 *  but also as more commonly used in computing - e.g. dynamic graphs.    *
 *  It interfaces with JGraphT, an API for mathematical graphs, and       *
 *  GraphStream, an API for visual graphs.                                *
 *                                                                        *
 **************************************************************************                                       
 *  This file is part of OMUGI (One More Ultimate Graph Implementation).  *
 *                                                                        *
 *  OMUGI is free software: you can redistribute it and/or modify         *
 *  it under the terms of the GNU General Public License as published by  *
 *  the Free Software Foundation, either version 3 of the License, or     *
 *  (at your option) any later version.                                   *
 *                                                                        *
 *  OMUGI is distributed in the hope that it will be useful,              *
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *  GNU General Public License for more details.                          *                         
 *                                                                        *
 *  You should have received a copy of the GNU General Public License     *
 *  along with OMUGI.  If not, see <https://www.gnu.org/licenses/gpl.html>*
 *                                                                        *
 **************************************************************************/
package au.edu.anu.rscs.aot.collections.tables;

/**
 * This code was generated by ../../codeGenerators/genPrimitiveClasses.py on Thu Aug 21 10:32:35 2014
 *
 */
/** modified by JG 15/2/2017 to account for Table and DataContainer interfaces */ 
public class ByteTable extends TableAdapter {

	protected byte[] data;

	public ByteTable(Dimensioner... dimensions) {
		super(dimensions);
		data = new byte[size()];
	}

	public byte getByInt(int... indexes) {
		return data[getFlatIndexByInt(indexes)];
	}

	public void setByInt(byte value, int... indexes) {
		data[getFlatIndexByInt(indexes)] = value;
	}

	public byte getWithFlatIndex(int index) {
		return data[index];
	}

	public void setWithFlatIndex(byte value, int index) {
		data[index] = value;
	}

	public byte get(Object... indexes) {
		return data[getFlatIndex(indexes)];
	}

	public void set(byte value, Object... indexes) {
		data[getFlatIndex(indexes)] = value;
	}


	@Override
	public ByteTable clone() {
		ByteTable result = cloneStructure();
		result.copy(this);
		return result;
	}
	
	@Override
	public ByteTable cloneStructure() {
		ByteTable result = new ByteTable(getDimensioners());
		return result;
	}

	public ByteTable cloneStructure(byte initialValue) {
		ByteTable result = cloneStructure();
		result.fillWith(initialValue);
		return result;
	}
	
	public ByteTable fillWith(byte value) {
		for (int i=0; i<data.length; i++)
			data[i] = value;
		return this;
	}
	
	@Override
	public String elementToString(int flatIndex) {
		return String.valueOf(data[flatIndex]);
	}

	@Override
	public ByteTable clear() {
		byte b = 00;
		fillWith(b); // this stupid dam thing wont accept a constant !
		return this;
	}

	@Override
	public ByteTable fillWith(Object value) {
		return fillWith(((Byte)value).byteValue());
	}

	@Override
	public ByteTable copy(TableAdapter from) {
		if (Byte.class.isAssignableFrom(from.contentType())) {
			ByteTable bt = (ByteTable)from;
			for (int i=0; i<data.length; i++)
				data[i] = bt.data[i];
		}
		return this;
	}

	@Override
	public String elementClassName() {
		return Byte.class.getName();
	}

	@Override
	public String elementSimpleClassName() {
		return Byte.class.getSimpleName();
	}

	@Override
	public Class<?> contentType() {
		return Byte.class;
	}
	
	public static ByteTable valueOf(String value, char[][] bdel, char[] isep) {
		String ss = TableAdapter.getBlockContent(value,bdel[TABLE]);
		String d = ss.substring(0,ss.indexOf(bdel[DIM][BLOCK_CLOSE])+1); 
		ByteTable result = new ByteTable(readDimensioners(d,bdel[DIM],isep[DIM]));
		ss = ss.substring(ss.indexOf(bdel[DIM][BLOCK_CLOSE])+1);
		String s = null;
		int i=0;
		while (ss.indexOf(isep[TABLE])>0) {
			s = ss.substring(0,ss.indexOf(isep[TABLE]));
			ss = ss.substring(ss.indexOf(isep[TABLE])+1);
			result.data[i] = Byte.valueOf(s);
			i++;
		}
		result.data[i] = Byte.valueOf(ss);
		return result;
	}

}
